# Generated by Django 3.2.9 on 2025-05-16 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oaiharvests', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='collection',
            name='description',
            field=models.TextField(blank=True, default='', help_text='Provide a short description of this collection.'),
        ),
        migrations.AddField(
            model_name='collection',
            name='edited_by',
            field=models.TextField(blank=True, default='', help_text='Enter editor names (first then last). Separate multiple editor names with a comma.'),
        ),
        migrations.AddField(
            model_name='collection',
            name='special_issue',
            field=models.BooleanField(default=False, help_text='Check on to indicate that this is a Special Issue'),
        ),
    ]
